name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.0.0
  carousel_slider: ^4.2.1
  uuid: ^4.5.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - test/test_assets/images/classic_beanie/
    - test/test_assets/images/classic_cap/
    - test/test_assets/images/classic_hoodie/
    - test/test_assets/images/classic_rainbow_hoodie/
    - test/test_assets/images/classic_sweatshirt/
    - test/test_assets/images/classic_tee/
    - test/test_assets/images/essential_tee/
    - test/test_assets/images/grad_hoodie/
    - test/test_assets/images/merch/
    - test/test_assets/images/print_shack/
    - test/test_assets/images/signature_hoodie/
    - test/test_assets/images/signature_tee/